
server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update